layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

repositories:
  - OpenVINO-18.04-Support
  - Granite
  - SP-Siri-Shortcuts
  - OpenAI-CartPole-v0
  - xBoot
  - ML-Antivirus
  - Color-Trek
  - dirm
  - amber-and-snake

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: nikhilraghavendra
  medium: "@nikraghava"
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: maranacoder
  # youtube: your_username
  # vk: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/8fb8b0e9d61d266721825ce116060773ea2503c2/topics/swift/swift.png

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/a3520d60fbf9b0bdd0b7d563a1a3ed596acd8489/topics/android/android.png

  - name: TensorFlow
    web_url: https://github.com/topics/tensorflow
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/tensorflow/tensorflow.png

  - name: scikit-learn
    web_url: https://github.com/topics/scikit-learn
    image_url: https://raw.githubusercontent.com/github/explore/cfd3599f6002d091325882369e7937113f792e58/topics/scikit-learn/scikit-learn.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/docker/docker.png

  - name: Arduino
    web_url: https://github.com/topics/arduino
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/arduino/arduino.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/linux/linux.png

  - name: Amazon Web Services
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
  
